export const COLOR_BRAND_BLUE = '#005792';
export const COLOR_BRAND_GREEN = '#0297A9';
export const COLOR_BACKGROUND_BLACK = '#414042';
export const COLOR_LIGHT_BACKGROUND = '#dcddde';
export const COLOR_MENU_FONT = '#747276';
export const COLOR_ERROR = '#CC0000';

const COLOR_NEW = '#815517';
const COLOR_FIXED = '#0297A9';

export const COLOR_FORCE_GRAPH_NODE_BACKGROUND = 'rgba(255, 255, 255, 0.8)';
export const COLOR_FORCE_GRAPH_NODE_THREAT = '#FA541C';
export const COLOR_FORCE_GRAPH_NODE_ASSET_NEW = COLOR_NEW;
export const COLOR_FORCE_GRAPH_NODE_ASSET_FIXED = COLOR_FIXED;
export const COLOR_FORCE_GRAPH_NODE_KILL_CHAIN = '#FF0000';
export const COLOR_TIMELINE_NEW = COLOR_NEW;
export const COLOR_TIMELINE_FIXED = COLOR_FIXED;
export const COLOR_COUNTRY_HOVER = COLOR_BRAND_GREEN;
export const COLOR_TIMELINE_ALL = '#8b8b8b';
export const COLOR_TOOLBAR_BACKGROUND = '#fafafa';
// New asset
export const COLOR_ASSET_THREAT_NEW_COLOR = '#881010';
export const COLOR_ASSET_THREAT_NEW_BACKGROUND = '#ffe9e9';
export const COLOR_ASSET_THREAT_NEW_COLOR_H = '#7d0707';
// Fixet asset
export const COLOR_ASSET_THREAT_FIXED_COLOR = '#808080';
export const COLOR_ASSET_THREAT_FIXED_BACKGROUND = '#f9f9f9';
export const COLOR_ASSET_THREAT_FIXED_BORDER = '#b7b7b7';

export const COLOR_SMALL_SPINNER = '#FFF';
export const COLOR_BOX_INNER_BORDER = COLOR_LIGHT_BACKGROUND;
export const COLOR_BOX_CONTENT = COLOR_LIGHT_BACKGROUND;
export const COLOR_BOX_HEADER = COLOR_BRAND_GREEN;
export const COLOR_BOX_GRAPH = COLOR_BRAND_BLUE;
/* export const COLOR_BOX_INNER_BORDER = '#76a4a9'; */
/*
export const COLOR_ANT_MENU = COLOR_LIGHT_BACKGROUND;
export const COLOR_ANT_MENU_FONT = COLOR_BRAND_BLUE;
export const COLOR_ANT_MENU_FONT_HOVER = COLOR_BRAND_GREEN;
*/
export const COLOR_ANT_MENU = COLOR_BRAND_BLUE;
export const COLOR_ANT_MENU_FONT = COLOR_LIGHT_BACKGROUND;
export const COLOR_ANT_MENU_FONT_HOVER = '#fff';
