const SAVE_FILTER_SET_REQUEST = 'APP/COMPONENTS/SAVE_FILTER_SET_REQUEST';
const SAVE_FILTER_SET_SUCCESS = 'APP/COMPONENTS/SAVE_FILTER_SET_SUCCESS';
const SAVE_FILTER_SET_FAILURE = 'APP/COMPONENTS/SAVE_FILTER_SET_FAILURE';

export default {
  SAVE_FILTER_SET_REQUEST,
  SAVE_FILTER_SET_SUCCESS,
  SAVE_FILTER_SET_FAILURE,
};
