# Copyright(C) 2021, Stamus Networks
# Written by Raphaël Brogat <rbrogat@stamus-networks.com>
#
# This file comes with ABSOLUTELY NO WARRANTY!
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

networks:
    network:

configs:
    opensearch-config:
        file: docker/configs/opensearch/opensearch.yml
    opensearch-dashboard-config:
        file: docker/configs/opensearch_dashboards/opensearch_dashboards.yml
    fluentd-config:
        file: docker/configs/fluentd/fluent.conf
    fluentd-template:
        file: docker/configs/fluentd/template.json
    suricata-entrypoint:
        file: docker/configs/suricata/new_entrypoint.sh
    suricata-config:
        file: docker/configs/suricata/selks6-addin.yaml

volumes:
    elastic-data: #for ES data persistency
    suricata-rules: #for suricata rules transfer between scirius and suricata and for persistency
    scirius-data: #for scirius data persistency
    scirius-static: #statics files to be served by nginx
    suricata-run: #path where the suricata socket resides
    suricata-logs:
    suricata-logrotate:
        driver_opts:
            type: none
            o: bind
            device: ./docker/containers-data/suricata/logrotate
    logstash-sincedb: #where logstash stores it's state so it doesn't re-ingest
    arkime-logs:
    arkime-pcap:
    arkime-config:
    db-data:
    fluentd-pos:
    scirius-tmp:

services:
    elasticsearch:
        image: opensearchproject/opensearch:2.19.0
        container_name: elasticsearch
        restart: ${RESTART_MODE:-unless-stopped}
        healthcheck:
            test: ['CMD-SHELL', 'curl -k --silent --fail http://localhost:9200/_cluster/health?waitforstatus=green&timeout=1s || exit 1']
            interval: 10s
            timeout: 5s
            retries: 3
            start_period: 30s
        environment:
            - DISABLE_SECURITY_PLUGIN=true
            # - XLOGGING_LEVEL=DEBUG
            # - OPENSEARCH_SSL_ENABLED=false
            # - OPENSEARCH_SSL_VERIFY_PEER=false
            # - OPENSEARCH_SSL_VERIFY_CA=false
            - cluster.name=opensearch-cluster
            - node.name=elasticsearch
            - discovery.seed_hosts=elasticsearch
            - cluster.initial_cluster_manager_nodes=elasticsearch
            - bootstrap.memory_lock=true
            - OPENSEARCH_JAVA_OPTS=-Xms1024m -Xmx1024m
            - OPENSEARCH_INITIAL_ADMIN_PASSWORD=YH8pq2lqNSnVEQZ
        volumes:
            - ${ELASTIC_DATAPATH:-elastic-data}:/usr/share/opensearch/data
        ports:
            - 9200:9200
            - 9600:9600  # required for Performance Analyzer
        mem_limit: ${ELASTIC_MEMORY:-3G}
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        networks:
            network:

    kibana:
        build:
            context: docker/opensearch-dashboards
            dockerfile: Dockerfile
        restart: ${RESTART_MODE:-unless-stopped}
        configs:
            - source: opensearch-dashboard-config
              target: /usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
        healthcheck:
            test: ['CMD-SHELL', 'curl --silent --fail http://localhost:5601 || exit 1']
            interval: 30s
            timeout: 5s
            retries: 3
            start_period: 30s
        environment:
            XLOGGING_LEVEL: DEBUG
            OPENSEARCH_SSL_ENABLED: false
            OPENSEARCH_SSL_VERIFY_CA: false
            OPENSEARCH_SSL_VERIFY_PEER: false
            OPENSEARCH_HOSTS: '["http://elasticsearch:9200"]'
        depends_on:
            elasticsearch:
                condition: service_healthy
        ports:
            - 5601:5601
        expose:
            - '5601'
        networks:
            network:

    fluentd:
        build:
            context: docker/fluentd
            dockerfile: Dockerfile
        command: fluentd -c /fluentd/etc/fluent.conf
        configs:
            - source: fluentd-config
              target: /fluentd/etc/fluent.conf
            - source: fluentd-template
              target: /fluentd/etc/template.json
        volumes:
            - fluentd-pos:/fluentd/log/td-agent/
            - suricata-logs:/var/log/suricata:ro
        networks:
            network:

    scirius:
        build:
            context: '.'
            dockerfile: Dockerfile.local
        restart: ${RESTART_MODE:-unless-stopped}
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:8000/']
            interval: 10s
            timeout: 1s
            retries: 5
            start_period: 5m
        environment:
            - SECRET_KEY=${SCIRIUS_SECRET_KEY:-$(openssl rand -hex 32)}
            - DEBUG=${SCIRIUS_DEBUG:-True}
            - SCIRIUS_IN_SELKS=True
            # check scirius.settings.DATA_LIKE
            - USE_DATA_LIKE=OPENSEARCH_2
            - ELASTICSEARCH_VERIFY_CERTS=True
            - USE_KIBANA=True
            - ALLOWED_HOSTS=* #allow connexions from anywhere
            - KIBANA7_DASHBOARDS_PATH=/opt/selks/kibana7-dashboards #where to find kibana dashboards
            - SURICATA_UNIX_SOCKET=/var/run/suricata/suricata-command.socket #socket to control suricata
            - USE_EVEBOX=True #gives access to evebox in the top menu
            - EVEBOX_ADDRESS=evebox:5636 #Default
            - USE_SURICATA_STATS=True #display more informations on the suricata page
            - USE_MOLOCH=True
            - MOLOCH_URL=http://arkime:8005
            - DATABASE_TYPE=pg
            - DATABASE_NAME=selks
            - DATABASE_USERNAME=selks
            - DATABASE_PASSWORD=selks
            - DATABASE_HOST=db
            - DATABASE_PORT=5432
            - RULESET_MIDDLEWARE=appliances
        volumes:
            - scirius-static:/static/
            - scirius-data:/data/
            - scirius-tmp:/tmp
            - suricata-rules:/rules
            - suricata-run:/var/run/suricata
            - ./docker/containers-data/scirius/logs/:/logs/
            - ./docker/containers-data/suricata/logs:/var/log/suricata:ro
            - ./docker/containers-data/scirius/license/:/data/license/
            - ./:/code/
        networks:
            network:
        ports:
            - 8000:8000
        depends_on:
            db:
                condition: service_healthy
            elasticsearch:
                condition: service_healthy

    db:
        image: postgres
        restart: always
        shm_size: 128mb
        environment:
            POSTGRES_USER: selks
            POSTGRES_PASSWORD: selks
        volumes:
            - db-data:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U selks']
            interval: 5s
            timeout: 1s
            retries: 5
        networks:
            network:

    celery-worker:
        build:
            context: '.'
            dockerfile: Dockerfile.local
        restart: always
        working_dir: /code
        entrypoint: celery
        command: -A suricata worker --loglevel=info
        environment:
            - SECRET_KEY=c8c0d898133cd973ea6a7b7a14c377bbb12dddc574c3ccaa
            - DATABASE_NAME=selks
            - DATABASE_USERNAME=selks
            - DATABASE_PASSWORD=selks
            - DATABASE_HOST=db
            - DATABASE_PORT=5432
        volumes:
            - scirius-data:/data/
            - suricata-rules:/rules
            - suricata-run:/var/run/suricata
            - scirius-tmp:/tmp
            - ./docker/containers-data/scirius/logs/:/logs/
            - ./docker/containers-data/suricata/etc:/etc/suricata
            - ./:/code/
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'celery --broker=amqp://guest:guest@rabbitmq:5672// -A suricata inspect ping',
                ]
            interval: 30s
            timeout: 10s
            retries: 3
        depends_on:
            rabbitmq:
                condition: service_healthy
        networks:
            network:

    celery-flower:
        build:
            context: '.'
            dockerfile: Dockerfile.local
        restart: always
        entrypoint: celery
        command: --broker=amqp://guest:guest@rabbitmq:5672// flower -A suricata
        environment:
            - SECRET_KEY=c8c0d898133cd973ea6a7b7a14c377bbb12dddc574c3ccaa
        depends_on:
            scirius:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
            celery-worker:
                condition: service_healthy
        ports:
            - 5555:5555
        networks:
            network:

    rabbitmq:
        image: rabbitmq:3-management-alpine
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 30s
            timeout: 30s
            retries: 3
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            network:
