# Generated by Django 3.2.13 on 2022-04-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suricata', '0005_django-2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suricata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
