# Generated by Django 3.2.25 on 2024-09-12 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suricata', '0006_alter_suricata_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_id', models.CharField(blank=True, max_length=36, null=True)),
                ('task', models.CharField(max_length=150)),
                ('task_options', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('running', 'Running'), ('finished', 'Finished'), ('revoked', 'Canceled')], default='scheduled', max_length=15)),
                ('is_recurrent', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('fired', models.DateTimeField(blank=True, null=True, verbose_name='last fired date')),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('retry', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('run_from_command', models.BooleanField(default=False)),
                ('children', models.ManyToManyField(related_name='parents', to='suricata.CeleryTask')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celerytask_suricata', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecurrentTask',
            fields=[
                ('celerytask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='suricata.celerytask')),
                ('scheduled', models.DateTimeField(verbose_name='schedule date')),
                ('recurrence', models.CharField(choices=[('hourly', 'hourly'), ('daily', 'daily'), ('monthly', 'monthly')], default='daily', max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('suricata.celerytask', models.Model),
        ),
        migrations.CreateModel(
            name='CeleryTaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='execution date')),
                ('status', models.CharField(choices=[('failed', 'Failure'), ('unreachable', 'Unreachable'), ('warning', 'Warning'), ('success', 'Success')], max_length=15)),
                ('message', models.TextField(blank=True, null=True)),
                ('retry_no', models.PositiveIntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suricata.celerytask')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='celerytask',
            name='rtask_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rtask_children', to='suricata.recurrenttask'),
        ),
        migrations.RemoveField(
            model_name='suricata',
            name='output_directory',
        ),
        migrations.RemoveField(
            model_name='suricata',
            name='yaml_file',
        ),
    ]
