# Generated by Django 4.2.16 on 2024-11-18 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suricata', '0007_auto_20240912_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celerytask',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_%(app_label)s', to=settings.AUTH_USER_MODEL),
        ),
    ]
