const FILTER_SETS_REQUEST = 'ui/store/filterSet/FILTER_SETS_REQUEST';
const FILTER_SETS_SUCCESS = 'ui/store/filterSet/FILTER_SETS_SUCCESS';
const FILTER_SETS_FAIL = 'ui/store/filterSet/FILTER_SETS_FAIL';
const DELETE_FILTER_SET = 'ui/store/filterSet/DELETE_FILTER_SET';
const DELETE_FILTER_SET_SUCCESS = 'ui/store/filterSet/DELETE_FILTER_SET_SUCCESS';
const DELETE_FILTER_SET_FAIL = 'ui/store/filterSet/DELETE_FILTER_SET_FAIL';

export default {
  FILTER_SETS_REQUEST,
  FILTER_SETS_SUCCESS,
  FILTER_SETS_FAIL,
  DELETE_FILTER_SET,
  DELETE_FILTER_SET_SUCCESS,
  DELETE_FILTER_SET_FAIL,
};
