const FILTER_SETS_REQUEST = 'ui/store/filterSet/FILTER_SETS_REQUEST';
const FILTER_SETS_SUCCESS = 'ui/store/filterSet/FILTER_SETS_SUCCESS';
const FILTER_SETS_FAIL = 'ui/store/filterSet/FILTER_SETS_FAIL';
const DELETE_FILTER_SET_CONFIRM = 'ui/store/filterSet/DELETE_FILTER_SET_CONFIRM';
const DELETE_FILTER_SET_REQUEST = 'ui/store/filterSet/DELETE_FILTER_SET_REQUEST';
const DELETE_FILTER_SET_SUCCESS = 'ui/store/filterSet/DELETE_FILTER_SET_SUCCESS';
const DELETE_FILTER_SET_FAILURE = 'ui/store/filterSet/DELETE_FILTER_SET_FAILURE';

export default {
  FILTER_SETS_REQUEST,
  FILTER_SETS_SUCCESS,
  FILTER_SETS_FAIL,
  DELETE_FILTER_SET_CONFIRM,
  DELETE_FILTER_SET_REQUEST,
  DELETE_FILTER_SET_SUCCESS,
  DELETE_FILTER_SET_FAILURE,
};
