# Generated by Django 2.2.17 on 2021-03-26 10:06

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='priority',
            field=models.IntegerField(default=accounts.models.get_next_priority),
        ),
    ]
