# Generated by Django 3.2.20 on 2024-02-22 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220412_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='SciriusTokenUser',
            fields=[
                ('sciriususer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.sciriususer')),
                ('description', models.CharField(default='', max_length=4096)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokenusers', to='accounts.sciriususer')),
            ],
            bases=('accounts.sciriususer',),
        ),
    ]
