const RULE_SETS_REQUEST = 'APP/STORES/FILTERS/RULE_SETS_REQUEST';
const RULE_SETS_SUCCESS = 'APP/STORES/FILTERS/RULE_SETS_SUCCESS';
const RULE_SETS_FAILURE = 'APP/STORES/FILTERS/RULE_SETS_FAILURE';

const SUPPORTED_ACTIONS_REQUEST = 'APP/STORES/FILTERS/SUPPORTED_ACTIONS_REQUEST';
const SUPPORTED_ACTIONS_SUCCESS = 'APP/STORES/FILTERS/SUPPORTED_ACTIONS_SUCCESS';
const SUPPORTED_ACTIONS_FAILURE = 'APP/STORES/FILTERS/SUPPORTED_ACTIONS_FAILURE';

const HISTORY_FILTERS_REQUEST = 'APP/STORES/FILTERS/HISTORY_FILTERS_REQUEST';
const HISTORY_FILTERS_SUCCESS = 'APP/STORES/FILTERS/HISTORY_FILTERS_SUCCESS';
const HISTORY_FILTERS_FAILURE = 'APP/STORES/FILTERS/HISTORY_FILTERS_FAILURE';

const MODAL_SAVE_FILTERS = 'APP/STORES/FILTERS/MODAL_SAVE_FILTERS';

export default {
  RULE_SETS_REQUEST,
  RULE_SETS_SUCCESS,
  RULE_SETS_FAILURE,
  SUPPORTED_ACTIONS_REQUEST,
  SUPPORTED_ACTIONS_SUCCESS,
  SUPPORTED_ACTIONS_FAILURE,
  HISTORY_FILTERS_REQUEST,
  HISTORY_FILTERS_SUCCESS,
  HISTORY_FILTERS_FAILURE,
  MODAL_SAVE_FILTERS,
};
