const RULE_SETS_REQUEST = 'APP/STORES/FILTERS/RULE_SETS_REQUEST';
const RULE_SETS_SUCCESS = 'APP/STORES/FILTERS/RULE_SETS_SUCCESS';
const RULE_SETS_FAILURE = 'APP/STORES/FILTERS/RULE_SETS_FAILURE';

const HUNT_FILTER_REQUEST = 'APP/STORES/FILTERS/HUNT_FILTER_REQUEST';
const HUNT_FILTER_SUCCESS = 'APP/STORES/FILTERS/HUNT_FILTER_SUCCESS';
const HUNT_FILTER_FAILURE = 'APP/STORES/FILTERS/HUNT_FILTER_FAILURE';

const SUPPORTED_ACTIONS_REQUEST = 'APP/STORES/FILTERS/SUPPORTED_ACTIONS_REQUEST';
const SUPPORTED_ACTIONS_SUCCESS = 'APP/STORES/FILTERS/SUPPORTED_ACTIONS_SUCCESS';
const SUPPORTED_ACTIONS_FAILURE = 'APP/STORES/FILTERS/SUPPORTED_ACTIONS_FAILURE';

export default {
  RULE_SETS_REQUEST,
  RULE_SETS_SUCCESS,
  RULE_SETS_FAILURE,
  HUNT_FILTER_REQUEST,
  HUNT_FILTER_SUCCESS,
  HUNT_FILTER_FAILURE,
  SUPPORTED_ACTIONS_REQUEST,
  SUPPORTED_ACTIONS_SUCCESS,
  SUPPORTED_ACTIONS_FAILURE,
}
