const LOCATION_CHANGE = '@@router/LOCATION_CHANGE';
const GET_PERIOD_ALL_REQUEST = 'ui/App/GET_PERIOD_ALL_REQUEST';
const GET_PERIOD_ALL_SUCCESS = 'ui/App/GET_PERIOD_ALL_SUCCESS';
const GET_PERIOD_ALL_FAILURE = 'ui/App/GET_PERIOD_ALL_FAILURE';
const SET_TIME_SPAN = 'ui/App/SET_TIME_SPAN';
const SET_DURATION = 'ui/App/SET_DURATION';
const SET_RELOAD = 'ui/App/SET_RELOAD';
const SET_FILTER_SETS = 'ui/App/SET_FILTER_SETS';
const DO_RELOAD = 'ui/App/DO_RELOAD';
const SET_SESSION_ACTIVITY_REQUEST = 'ui/App/SET_SESSION_ACTIVITY_REQUEST';
const SET_SESSION_ACTIVITY_FAILURE = 'ui/App/SET_SESSION_ACTIVITY_FAILURE';
const UPDATE_PUSH_RULESET_RESET = 'ui/App/UPDATE_PUSH_RULESET_RESET';
const UPDATE_PUSH_RULESET_REQUEST = 'ui/App/UPDATE_PUSH_RULESET_REQUEST';
const UPDATE_PUSH_RULESET_SUCCESS = 'ui/App/UPDATE_PUSH_RULESET_SUCCESS';
const UPDATE_PUSH_RULESET_FAILURE = 'ui/App/UPDATE_PUSH_RULESET_FAILURE';

export default {
  LOCATION_CHANGE,
  SET_TIME_SPAN,
  SET_DURATION,
  SET_RELOAD,
  SET_FILTER_SETS,
  DO_RELOAD,
  GET_PERIOD_ALL_REQUEST,
  GET_PERIOD_ALL_SUCCESS,
  GET_PERIOD_ALL_FAILURE,
  SET_SESSION_ACTIVITY_REQUEST,
  SET_SESSION_ACTIVITY_FAILURE,
  UPDATE_PUSH_RULESET_RESET,
  UPDATE_PUSH_RULESET_REQUEST,
  UPDATE_PUSH_RULESET_SUCCESS,
  UPDATE_PUSH_RULESET_FAILURE,
};
