const LOCATION_CHANGE = '@@router/LOCATION_CHANGE';
const GET_USER_REQUEST = 'ui/App/GET_USER_REQUEST';
const GET_USER_SUCCESS = 'ui/App/GET_USER_SUCCESS';
const GET_USER_FAILURE = 'ui/App/GET_USER_FAILURE';
const GET_SYSTEM_SETTINGS_REQUEST = 'ui/App/GET_SYSTEM_SETTINGS_REQUEST';
const GET_SYSTEM_SETTINGS_SUCCESS = 'ui/App/GET_SYSTEM_SETTINGS_SUCCESS';
const GET_SYSTEM_SETTINGS_FAILURE = 'ui/App/GET_SYSTEM_SETTINGS_FAILURE';
const GET_SOURCE_REQUEST = 'ui/App/GET_SOURCE_REQUEST';
const GET_PERIOD_ALL_REQUEST = 'ui/App/GET_PERIOD_ALL_REQUEST';
const GET_PERIOD_ALL_SUCCESS = 'ui/App/GET_PERIOD_ALL_SUCCESS';
const GET_PERIOD_ALL_FAILURE = 'ui/App/GET_PERIOD_ALL_FAILURE';
const GET_SOURCE_SUCCESS = 'ui/App/GET_SOURCE_SUCCESS';
const GET_SOURCE_FAILURE = 'ui/App/GET_SOURCE_FAILURE';
const SET_TIME_SPAN = 'ui/App/SET_TIME_SPAN';
const SET_DURATION = 'ui/App/SET_DURATION';
const SET_RELOAD = 'ui/App/SET_RELOAD';
const SET_FILTER_SETS = 'ui/App/SET_FILTER_SETS';
const DO_RELOAD = 'ui/App/DO_RELOAD';
const SET_SESSION_ACTIVITY_REQUEST = 'ui/App/SET_SESSION_ACTIVITY_REQUEST';
const SET_SESSION_ACTIVITY_FAILURE = 'ui/App/SET_SESSION_ACTIVITY_FAILURE';

export default {
  LOCATION_CHANGE,
  GET_USER_REQUEST,
  GET_USER_SUCCESS,
  GET_USER_FAILURE,
  GET_SYSTEM_SETTINGS_REQUEST,
  GET_SYSTEM_SETTINGS_SUCCESS,
  GET_SYSTEM_SETTINGS_FAILURE,
  GET_SOURCE_REQUEST,
  GET_SOURCE_SUCCESS,
  GET_SOURCE_FAILURE,
  SET_TIME_SPAN,
  SET_DURATION,
  SET_RELOAD,
  SET_FILTER_SETS,
  DO_RELOAD,
  GET_PERIOD_ALL_REQUEST,
  GET_PERIOD_ALL_SUCCESS,
  GET_PERIOD_ALL_FAILURE,
  SET_SESSION_ACTIVITY_REQUEST,
  SET_SESSION_ACTIVITY_FAILURE,
};
