const LOCATION_CHANGE = '@@router/LOCATION_CHANGE';
const GET_USER_REQUEST = 'ui/App/GET_USER_REQUEST';
const GET_USER_SUCCESS = 'ui/App/GET_USER_SUCCESS';
const GET_USER_FAILURE = 'ui/App/GET_USER_FAILURE';
const GET_SETTINGS_REQUEST = 'ui/App/GET_SETTINGS_REQUEST';
const GET_SETTINGS_SUCCESS = 'ui/App/GET_SETTINGS_SUCCESS';
const GET_SETTINGS_FAILURE = 'ui/App/GET_SETTINGS_FAILURE';
const GET_SOURCE_REQUEST = 'ui/App/GET_SOURCE_REQUEST';
const GET_PERIOD_ALL_REQUEST = 'ui/App/GET_PERIOD_ALL_REQUEST';
const GET_PERIOD_ALL_SUCCESS = 'ui/App/GET_PERIOD_ALL_SUCCESS';
const GET_PERIOD_ALL_FAILURE = 'ui/App/GET_PERIOD_ALL_FAILURE';
const GET_SOURCE_SUCCESS = 'ui/App/GET_SOURCE_SUCCESS';
const GET_SOURCE_FAILURE = 'ui/App/GET_SOURCE_FAILURE';
const SET_TIME_SPAN = 'ui/App/SET_TIME_SPAN';
const SET_DURATION = 'ui/App/SET_DURATION';
const SET_RELOAD = 'ui/App/SET_RELOAD';
const DO_RELOAD = 'ui/App/DO_RELOAD';

export default {
  LOCATION_CHANGE,
  GET_USER_REQUEST,
  GET_USER_SUCCESS,
  GET_USER_FAILURE,
  GET_SETTINGS_REQUEST,
  GET_SETTINGS_SUCCESS,
  GET_SETTINGS_FAILURE,
  GET_SOURCE_REQUEST,
  GET_SOURCE_SUCCESS,
  GET_SOURCE_FAILURE,
  SET_TIME_SPAN,
  SET_DURATION,
  SET_RELOAD,
  DO_RELOAD,
  GET_PERIOD_ALL_REQUEST,
  GET_PERIOD_ALL_SUCCESS,
  GET_PERIOD_ALL_FAILURE,
}
