const GET_BLOCK_MORE_RESULTS_REQUEST = 'APP/STORES/DASHBOARD/GET_BLOCK_MORE_RESULTS_REQUEST';
const GET_BLOCK_MORE_RESULTS_SUCCESS = 'APP/STORES/DASHBOARD/GET_BLOCK_MORE_RESULTS_SUCCESS';
const GET_BLOCK_MORE_RESULTS_FAILURE = 'APP/STORES/DASHBOARD/GET_BLOCK_MORE_RESULTS_FAILURE';

const SET_MODAL_MORE_RESULTS = 'APP/STORES/DASHBOARD/SET_MODAL_MORE_RESULTS';
const DOWNLOAD_BLOCK_DATA = 'APP/STORES/DASHBOARD/DOWNLOAD_BLOCK_DATA';
const SET_EDIT_MODE = 'APP/STORES/DASHBOARD/SET_EDIT_MODE';

export default {
  GET_BLOCK_MORE_RESULTS_REQUEST,
  GET_BLOCK_MORE_RESULTS_SUCCESS,
  GET_BLOCK_MORE_RESULTS_FAILURE,
  SET_MODAL_MORE_RESULTS,
  DOWNLOAD_BLOCK_DATA,
  SET_EDIT_MODE,
};
