export const API_URL = '/';
export const RULE_PATH = 'rest/rules/rule/';
export const RULESET_PATH = 'rest/rules/ruleset/';
export const SOURCE_PATH = 'rest/rules/source/';
export const CATEGORY_PATH = 'rest/rules/category/';
export const HISTORY_PATH = 'rest/rules/history/';
export const PROCESSING_PATH = 'rest/rules/processing-filter/';
export const HUNT_FILTER_PATH = 'rest/rules/hunt-filter/';
export const SYSTEM_SETTINGS_PATH = 'rest/rules/system_settings/';
export const USER_PATH = 'rest/accounts/sciriususer/';
// export const URL = process.env.API_URL;
export const API_LOGIN = '/auth';

export const ES_BASE_PATH = 'rest/rules/es/';
export const ES_SIGS_LIST_PATH = `${ES_BASE_PATH}sigs_list/?hosts=*&offset=0&sids=`;
export const UPDATE_PUSH_RULESET_PATH = 'rest/suricata/update_push_all/';
export const SCIRIUS_CONTEXT = 'rest/rules/scirius_context/';
export const HUNT_DOC = '/static/doc/hunt.html';
export const HUNT_FILTER_SETS = 'rest/rules/hunt_filter_sets/';
export const FILESTORE_PATH = 'rest/rules/filestore/';
