/**
 *
 * PfIcon
 *
 */

import React from 'react';
import PropTypes from 'prop-types';
// import styled from 'styled-components';
import './style.css';

export const PfIcon = ({ type, style }) => <i className={`pficon-${type}`} style={style} />;
PfIcon.defaultProps = {
  style: {},
};

PfIcon.propTypes = {
  style: PropTypes.object,
  type: PropTypes.oneOf([
    'add-circle-o',
    'applications',
    'arrow',
    'asleep',
    'automation',
    'build',
    'builder-image',
    'bundle',
    'blueprint',
    'catalog',
    'chat',
    'close',
    'cloud-security',
    'cloud-tenant',
    'cluster',
    'connected',
    'container-node',
    'cpu',
    'degraded',
    'delete',
    'disconnected',
    'domain',
    'edit',
    'enhancement',
    'enterprise',
    'equalizer',
    'error-circle-o',
    'export',
    'flag',
    'messages',
    'flavor',
    'filter',
    'folder-close',
    'folder-open',
    'help',
    'history',
    'home',
    'image',
    'import',
    'in-progress',
    'info',
    'infrastructure',
    'integration',
    'key',
    'locked',
    'maintenance',
    'memory',
    'middleware',
    'migration',
    'monitoring',
    'network',
    'network-range',
    'on',
    'on-running',
    'optimize',
    'orders',
    'off',
    'ok',
    'paused',
    'pending',
    'plugged',
    'port',
    'print',
    'process-automation',
    'private',
    'project',
    'rebalance',
    'rebooting',
    'refresh',
    'restart',
    'regions',
    'registry',
    'remove',
    'replicator',
    'repository',
    'resource-pool',
    'resources-almost-empty',
    'resources-almost-full',
    'resources-full',
    'route',
    'running',
    'satellite',
    'save',
    'screen',
    'search',
    'security',
    'server',
    'server-group',
    'service',
    'services',
    'service-catalog',
    'settings',
    'sort-common-asc',
    'sort-common-desc',
    'spinner',
    'spinner2',
    'storage-domain',
    'template',
    'tenant',
    'thumb-tack-o',
    'topology',
    'trend-down',
    'trend-up',
    'unknown',
    'user',
    'users',
    'unlocked',
    'unplugged',
    'vcenter',
    'virtual-machine',
    'volume',
    'warning-triangle-o',
    'zone',
  ]).isRequired,
};

export default PfIcon;
