"""
Copyright(C) 2014-2018 Stamus Networks
Written by Eric Leblond <eleblond@stamus-networks.com>

This file is part of Scirius.

Scirius is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Scirius is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Scirius.  If not, see <http://www.gnu.org/licenses/>.
"""

from copy import deepcopy
from typing import NotRequired, TypedDict

from django.conf import settings
from django.contrib.auth.models import User
from django.db import models


class FilterSetContentDict(TypedDict):
    value: str | int
    label: str
    fullString: bool
    query: NotRequired[str]
    negated: bool
    id: str


class FilterSetDict(TypedDict):
    content: list[FilterSetContentDict]
    name: str
    page: str
    description: str


FILTER_SETS: list[FilterSetDict] = [
    {
        "content": [
            {
                "value": 1,
                "label": "Alerts min: 1",
                "fullString": True,
                "query": "rest",
                "negated": False,
                "id": "hits_min",
            },
            {
                "value": 10,
                "label": "Alerts max: 10",
                "fullString": True,
                "query": "rest",
                "negated": False,
                "id": "hits_max",
            },
        ],
        "name": "Hunt: Low noise signature events",
        "page": "RULES_LIST",
        "description": "This filter highlights the events which have rarely triggered. These low noise alerts can sometimes hide valuable artifacts and discoveries. Use case examples: This filter is a goldmine for threat hunters, as rarely-triggered signatures often represent highly specific detections of targeted attacks or sophisticated techniques that don't generate widespread alerts. Analysts can use it to discover anomalous activity that would otherwise be lost in high-volume detection feeds, often revealing stealthy adversaries.",
    },
    {
        "content": [
            {
                "value": "TROJAN",
                "label": "alert.signature: TROJAN",
                "fullString": False,
                "query": "filter",
                "negated": False,
                "id": "alert.signature",
            }
        ],
        "name": "Hunt: Trojan related events",
        "page": "DASHBOARDS",
        "description": "This filter highlights the trojan-related events. Use case examples: This filter provides a targeted view of trojan-specific detections, enabling analysts to assess the scope of a trojan infection and identify all affected hosts communicating with trojan C2 infrastructure. It supports incident response operations by providing a prioritized list of hosts that require immediate forensic investigation and remediation.",
    },
    {
        "content": [
            {
                "value": "MALWARE",
                "label": "alert.signature: MALWARE",
                "fullString": False,
                "query": "filter",
                "negated": False,
                "id": "alert.signature",
            }
        ],
        "name": "Hunt: Malware related events",
        "page": "DASHBOARDS",
        "description": "This filter highlights the malware-related events. Use case examples: This filter provides a broad sweep of all malware-related detections, making it an effective starting point for incident scope assessment and proactive threat hunting across the organization. Security teams can use it to identify active malware campaigns, track the spread of infections, and prioritize remediation efforts based on the volume and distribution of affected hosts.",
    },
    {
        "content": [
            {
                "value": "HUNTING",
                "label": "alert.signature: HUNTING",
                "fullString": False,
                "query": "filter",
                "negated": False,
                "id": "alert.signature",
            }
        ],
        "name": "Hunt: HUNTING related events",
        "page": "DASHBOARDS",
        "description": 'This filter highlights all the events that are generated from  rules with the "hunting" designation. Use case examples: This filter surfaces all events generated by hunting-designated signatures, making it a powerful broad sweep for the most research-oriented and novel threat detections in the ruleset. Analysts can use it as a discovery mechanism for newly observed attack techniques that haven\'t yet been promoted to high-confidence alert signatures.',
    },
    {
        "content": [
            {
                "value": "Executable",
                "label": "alert.signature: Executable",
                "fullString": False,
                "query": "filter",
                "negated": False,
                "id": "alert.signature",
            }
        ],
        "name": "Hunt: Executable related events",
        "page": "DASHBOARDS",
        "description": "This filter highlights all the events related to executable files, including downloads, posts, and others. This usually provides interesting data that warrants further investigation. Use case examples: Hunters can apply this filter to surface all executable-related network activity, providing a comprehensive view of potential malware delivery, lateral movement tools, and unauthorized software distribution. It is a powerful starting point for mapping how executable payloads are moving across the network during an active incident or as part of proactive threat hunting.",
    },
    {
        "content": [
            {
                "value": "Executable",
                "label": "alert.signature: Executable",
                "fullString": False,
                "query": "filter",
                "negated": False,
                "id": "alert.signature",
            },
            {
                "value": "http",
                "label": "app_proto: http",
                "fullString": False,
                "query": "filter_host_id",
                "negated": False,
                "id": "app_proto",
            },
        ],
        "name": "Hunt: HTTP Executable related events",
        "page": "DASHBOARDS",
        "description": "This filter highlights all the events that take place via HTTP and are either posting or downloading executables. Use case examples: This filter provides focused visibility into HTTP-based malware delivery and staging operations, enabling analysts to identify both downloads and uploads of executable content through the web layer. It is particularly effective for detecting web-based exploitation frameworks that leverage HTTP to deliver shellcode or droppers to victim systems.",
    },
    {
        "content": [
            {"id": "app_proto", "value": "http", "label": "app_proto: http", "fullString": True, "negated": False},
            {
                "label": "es_filter: ( http.hostname.keyword: /10\\..*\\..*\\..*/ OR http.hostname.keyword: /192\\.168\\..*\\..*/ OR  http.hostname.keyword: /172\\.<16-32>\\..*\\..*/ ) AND http.hostname.keyword: /([0-9]{1,3}\\.){3}[0-9]{1,3}/",
                "id": "es_filter",
                "value": "( http.hostname.keyword: /10\\..*\\..*\\..*/ OR http.hostname.keyword: /192\\.168\\..*\\..*/ OR  http.hostname.keyword: /172\\.<16-32>\\..*\\..*/ ) AND http.hostname.keyword: /([0-9]{1,3}\\.){3}[0-9]{1,3}/",
                "negated": False,
                "query": "filter",
                "fullString": False,
            },
        ],
        "name": "Hunt: HTTP direct requests and replies to private IP",
        "page": "DASHBOARDS",
        "description": "This filter highlights all the events that include HTTP requests and responses directly to an internal IP address - not a domain name. This activity may be suspicious because a domain name is typically part of the transaction when communicating with servers inside the network. While common in some development environments, it could also indicate lateral movement. Use case examples: This filter helps detect lateral movement where attackers communicate with internal web services directly by IP, bypassing DNS resolution and potentially evading URL-based security controls. It is particularly valuable for identifying attacker-controlled web servers or compromised internal hosts serving as C2 relay nodes within the corporate network.",
    },
    {
        "content": [
            {"id": "app_proto", "value": "http", "label": "app_proto: http", "fullString": True, "negated": False},
            {
                "label": "ES Filter: ( NOT http.hostname.keyword: /10\\..*\\..*\\..*/ AND NOT http.hostname.keyword: /192\\.168\\..*\\..*/ AND NOT http.hostname.keyword: /172\\.<16-32>\\..*\\..*/ ) AND http.hostname.keyword: /([0-9]{1,3}\\.){3}[0-9]{1,3}/",
                "id": "es_filter",
                "value": "( NOT http.hostname.keyword: /10\\..*\\..*\\..*/ AND NOT http.hostname.keyword: /192\\.168\\..*\\..*/ AND NOT http.hostname.keyword: /172\\.<16-32>\\..*\\..*/ ) AND http.hostname.keyword: /([0-9]{1,3}\\.){3}[0-9]{1,3}/",
                "negated": False,
                "query": "filter",
                "fullString": False,
            },
        ],
        "name": "Hunt: HTTP non-internal  direct IP requests and replies",
        "page": "DASHBOARDS",
        "description": "This filter highlights all the events that indicate HTTP requests and responses directly by IP - not using a domain name. This activity may be suspicious because a domain name is typically part of the transaction when communicating with servers outside the network (non private/internal IPs). Use case examples: This filter helps detect malware beaconing to external C2 infrastructure using direct IP addresses instead of domain names, effectively bypassing DNS-based threat intelligence controls. It is also valuable for identifying data exfiltration attempts where attackers use hardcoded IP addresses to evade domain reputation filtering systems.",
    },
    {
        "content": [
            {"id": "app_proto", "value": "dns", "label": "app_proto: dns", "fullString": True, "negated": True},
            {
                "label": "ES Filter: payload_printable.keyword: *admin*",
                "id": "es_filter",
                "value": "payload_printable.keyword: *admin*",
                "negated": False,
                "query": "filter",
                "fullString": False,
            },
        ],
        "name": "Hunt: Admin payload search",
        "page": "DASHBOARDS",
        "description": 'This filter highlights the events that include "Admin" or "Administrator" in their alert payload. Use case examples: This filter helps detect brute-force attacks, unauthorized admin access attempts, or tools that probe for administrative interfaces across the network. It is useful in identifying post-compromise privilege escalation activity where an attacker is attempting to gain administrative control of discovered systems.',
    },
    {
        "content": [
            {"id": "app_proto", "value": "dns", "label": "app_proto: dns", "fullString": True, "negated": True},
            {
                "label": "es_filter: payload_printable.keyword: *root*",
                "id": "es_filter",
                "value": "payload_printable.keyword: *root*",
                "negated": False,
                "query": "filter",
                "fullString": False,
            },
        ],
        "name": "Hunt: Root payload search",
        "page": "DASHBOARDS",
        "description": 'This filter highlights the events containing "root" in the payloads. Use case examples: This filter helps analysts detect exploitation attempts and post-exploitation activity where "root" credentials or access contexts are referenced in network payloads, indicating privilege escalation attempts. It is particularly useful for identifying attacks targeting Linux and Unix systems where root access represents the highest privilege level sought by attackers.',
    },
    {
        "content": [
            {"id": "app_proto", "value": "http", "label": "app_proto: http", "fullString": True, "negated": False},
            {
                "label": "es_filter: payload_printable.keyword: *root* ",
                "id": "es_filter",
                "value": "payload_printable.keyword: *root* ",
                "negated": False,
                "query": "filter",
                "fullString": False,
            },
        ],
        "name": "Hunt: HTTP payloads containing root",
        "page": "DASHBOARDS",
        "description": 'This filter highlights all the events that indicate HTTP payloads containing "root". Use case examples: This filter helps detect exploitation attempts targeting root-level access on web servers or applications, as well as post-exploitation activity where root credentials are being used or validated over HTTP. Analysts can correlate these events with other indicators to determine whether a successful root-level compromise has occurred.',
    },
    {
        "content": [
            {"id": "app_proto", "value": "http", "label": "app_proto: http", "fullString": True, "negated": False},
            {
                "label": "es_filter: payload_printable.keyword: *admin* ",
                "id": "es_filter",
                "value": "payload_printable.keyword: *admin* ",
                "negated": False,
                "query": "filter",
                "fullString": False,
            },
        ],
        "name": "Hunt: HTTP payloads containing admin",
        "page": "DASHBOARDS",
        "description": 'This filter highlights all the events that indicate HTTP payloads containing "admin". Use case examples: Hunters can use this filter to identify unauthorized attempts to access administrative interfaces, brute-force admin credentials, or interact with admin panels across web applications in the environment. It is also effective for detecting web-based exploitation frameworks that target admin functionality to escalate privileges or deploy web shells on compromised servers.',
    },
    {
        "content": [
            {"id": "app_proto", "value": "tls", "label": "app_proto: tls", "fullString": True, "negated": False},
            {
                "label": "es_filter: payload_printable.keyword: *admin* OR payload_printable.keyword: *root* ",
                "id": "es_filter",
                "value": "payload_printable.keyword: *admin* OR payload_printable.keyword: *root* ",
                "negated": False,
                "query": "filter",
                "fullString": False,
            },
        ],
        "name": "Hunt: TLS payloads containing root or admin",
        "page": "DASHBOARDS",
        "description": 'This filter highlights the events identifying "root" or "admin" in the TLS payload. Use case examples: Hunters can use this filter to detect encrypted communications where "root" or "admin" strings appear in TLS handshake data or certificates, potentially indicating malicious infrastructure designed to look like legitimate administrative services. It also helps identify unauthorized administrative access channels that use TLS to encrypt communications and evade plaintext inspection controls.',
    },
    {
        "content": [
            {"id": "app_proto", "value": "tls", "label": "app_proto: tls", "fullString": True, "negated": False},
            {
                "id": "tls.version",
                "value": "TLS 1.2",
                "label": "tls.version: TLS 1.2",
                "fullString": True,
                "negated": True,
            },
            {
                "id": "tls.version",
                "value": "TLS 1.3",
                "label": "tls.version: TLS 1.3",
                "fullString": True,
                "negated": True,
            },
            {
                "id": "tls.version",
                "value": "UNDETERMINED",
                "label": "tls.version: UNDETERMINED",
                "fullString": True,
                "negated": True,
            },
        ],
        "name": "Policy: Old TLS versions",
        "page": "DASHBOARDS",
        "description": "This filter highlights events that identify the use of TLS encryption versions prior to version 1.2. Use case examples: This filter is essential for identifying hosts that are using deprecated TLS versions (1.0 or 1.1) that contain known cryptographic weaknesses exploitable by attacks like POODLE and BEAST. Analysts can use it to prioritize TLS hardening efforts and identify both clients and servers that require urgent configuration updates to meet current security standards.",
    },
    {
        "content": [
            {"id": "app_proto", "value": "ftp*", "label": "app_proto: ftp*", "fullString": False, "negated": False}
        ],
        "name": "Policy: FTP clear text alerts and sightings",
        "page": "DASHBOARDS",
        "description": "This filter highlights FTP events. Use case examples: This filter provides comprehensive visibility into FTP-related activity, enabling analysts to detect both the use of FTP and the transmission of credentials in cleartext, which is particularly dangerous on networks without full perimeter inspection. It helps security teams identify FTP-based data exfiltration attempts and unauthorized file transfers to external servers.",
    },
    {
        "content": [
            {
                "value": "post",
                "label": "http.http_method: post",
                "fullString": False,
                "query": "filter",
                "negated": False,
                "id": "http.http_method",
            }
        ],
        "name": "Hunt: HTTP POSTs",
        "page": "DASHBOARDS",
        "description": "This filter highlights all the events that include HTTP POST requests. This type of request can hide malicious activity. Use case examples: Hunters can use this filter to detect data exfiltration over HTTP POST requests, a common technique used by malware to transmit stolen credentials, files, or system information to attacker-controlled servers. It is also effective for uncovering C2 communications that use HTTP POST as a covert channel to receive commands and upload results.",
    },
    {
        "content": [
            {"id": "app_proto", "value": "smtp", "label": "app_proto: smtp", "fullString": False, "negated": False}
        ],
        "name": "Policy: SMTP clear text events",
        "page": "DASHBOARDS",
        "description": "This filter highlights clear text SMTP events. Use case examples: This filter helps detect email transmission that lacks encryption, creating risk of email interception, credential harvesting, and exposure of sensitive communications on the network path. Analysts can use it to identify mail servers and clients that require configuration updates to enforce TLS encryption for SMTP communications as per organizational policy.",
    },
    {
        "content": [
            {
                "value": "firefox*",
                "label": "http.http_user_agent: firefox*",
                "fullString": False,
                "query": "filter",
                "negated": True,
                "id": "http.http_user_agent",
            },
            {
                "value": "explorer*",
                "label": "http.http_user_agent: explorer*",
                "fullString": False,
                "query": "filter",
                "negated": True,
                "id": "http.http_user_agent",
            },
            {
                "value": "opera*",
                "label": "http.http_user_agent: opera*",
                "fullString": False,
                "query": "filter",
                "negated": True,
                "id": "http.http_user_agent",
            },
            {
                "value": "edge*",
                "label": "http.http_user_agent: edge*",
                "fullString": False,
                "query": "filter",
                "negated": True,
                "id": "http.http_user_agent",
            },
            {
                "value": "mozilla*",
                "label": "http.http_user_agent: mozilla*",
                "fullString": False,
                "query": "filter",
                "negated": True,
                "id": "http.http_user_agent",
            },
            {
                "value": "wget*",
                "label": "http.http_user_agent: wget*",
                "fullString": False,
                "query": "filter",
                "negated": True,
                "id": "http.http_user_agent",
            },
            {
                "value": "curl*",
                "label": "http.http_user_agent: curl*",
                "fullString": False,
                "query": "filter",
                "negated": True,
                "id": "http.http_user_agent",
            },
            {
                "value": "perl*",
                "label": "http.http_user_agent: perl*",
                "fullString": False,
                "query": "filter",
                "negated": True,
                "id": "http.http_user_agent",
            },
            {
                "value": "python*",
                "label": "http.http_user_agent: python*",
                "fullString": False,
                "query": "filter",
                "negated": True,
                "id": "http.http_user_agent",
            },
            {
                "value": "http",
                "label": "app_proto: http",
                "fullString": True,
                "query": "filter",
                "negated": False,
                "id": "app_proto",
            },
        ],
        "name": "Hunt: Suspicious HTTP User Agents - 1",
        "page": "DASHBOARDS",
        "description": "This filter highlights events that are using HTTP application layer protocol but with an user agent that includes specific characters not common to user agents. Use case examples: This filter helps detect malware, exploit frameworks, or attack tools that use HTTP user agent strings containing special characters or unusual syntax to communicate with C2 servers or conduct reconnaissance. Analysts can use it to identify non-browser HTTP clients that are attempting to blend into normal web traffic while conducting malicious operations.",
    },
    {
        "content": [
            {
                "value": "*(*",
                "label": "http.http_user_agent: *(*",
                "fullString": False,
                "query": "filter",
                "negated": True,
                "id": "http.http_user_agent",
            },
            {
                "value": "http",
                "label": "app_proto: http",
                "fullString": True,
                "query": "filter",
                "negated": False,
                "id": "app_proto",
            },
        ],
        "name": "Hunt: Suspicious HTTP User Agents -2",
        "page": "DASHBOARDS",
        "description": "This filter highlights events that are using HTTP application layer protocol but with an user agent that is not common - aka not mozilla/firefox/opera/edge/wget and similar. Use case examples: Hunters can use this filter to identify hosts running automated tools or malware that use uncommon or generic user agent strings not associated with standard browsers or legitimate applications. It is particularly useful for detecting custom-built attack tools and RATs that lack a convincing user agent string, making them stand out from legitimate browser-generated traffic.",
    },
    {
        "content": [
            {
                "value": "CURRENT_EVENTS",
                "label": "alert.signature: CURRENT_EVENTS",
                "fullString": False,
                "query": "filter",
                "negated": False,
                "id": "alert.signature",
            }
        ],
        "name": "Hunt: Current events",
        "page": "DASHBOARDS",
        "description": "This filter highlights the events that trigger based on the CURRENT_EVENTS ET rules. Use case examples: This filter helps hunters stay ahead of emerging threats by surfacing detections based on the most recently published signatures tracking active threat campaigns. It is particularly valuable during times of heightened threat activity, such as the exploitation of a newly disclosed zero-day vulnerability, enabling rapid assessment of exposure.",
    },
    {
        "content": [
            {
                "negated": False,
                "fullString": False,
                "id": f"{'dns.queries' if settings.SURICATA_VERSION == 8 else 'dns.query'}.rrname",
                "value": "*",
                "label": f"{'dns.queries' if settings.SURICATA_VERSION == 8 else 'dns.query'}.rrname: *",
            }
        ],
        "name": "Hunt: DNS related events",
        "page": "DASHBOARDS",
        "description": "This filter highlights all the events with DNS-related metadata. Use case examples: This filter provides a comprehensive view of DNS-related detections, making it an effective starting point for hunting DNS-based attack techniques such as DNS tunneling, DGA, and DNS rebinding. Analysts can use it to correlate DNS anomalies with other events to build a complete picture of attacker reconnaissance and communication patterns.",
    },
    {
        "content": [
            {
                "negated": True,
                "fullString": False,
                "id": "ssh.client.software_version",
                "value": "*ssh*",
                "label": "ssh.client.software_version: *ssh*",
            },
            {
                "value": "ssh",
                "label": "app_proto: ssh",
                "fullString": False,
                "query": "filter_host_id",
                "negated": False,
                "id": "app_proto",
            },
        ],
        "name": "Hunt: Non lib/open ssh clients",
        "page": "DASHBOARDS",
        "description": "This filter highlights the SSH-related events that have no libssh or openssh client version. Use case examples: This filter helps detect non-standard SSH clients that may indicate attacker tools, custom malware implants, or unauthorized administrative software accessing systems via SSH. It is also valuable for identifying IoT devices, embedded systems, or appliances using proprietary SSH implementations that may have unpatched vulnerabilities.",
    },
    {
        "content": [
            {
                "value": "python*",
                "label": "http.http_user_agent: python*",
                "fullString": False,
                "query": "filter",
                "negated": False,
                "id": "http.http_user_agent",
            }
        ],
        "name": "Info: Python HTTP User Agents",
        "page": "DASHBOARDS",
        "description": "This informational filter highlights the HTTP-based events that contain Python HTTP User Agents. Use case examples: This filter helps detect Python-based scripts, tools, or malware frameworks performing HTTP communications, including popular attack frameworks like Impacket or custom-built exploitation tools. Security teams can use it to identify hosts running unexpected Python-based automation that may indicate compromise, unauthorized scripting, or lateral movement using Python-based post-exploitation tools.",
    },
    {
        "content": [
            {
                "value": "curl*",
                "label": "http.http_user_agent: curl*",
                "fullString": False,
                "query": "filter",
                "negated": False,
                "id": "http.http_user_agent",
            }
        ],
        "name": "Info: Curl HTTP User Agents",
        "page": "DASHBOARDS",
        "description": "This informational filter highlights the HTTP-based events that contain Curl HTTP User Agents. Use case examples: Hunters can use this filter to identify hosts running curl-based automation or scripts that interact with web services, which may indicate legitimate DevOps tooling or attacker-controlled scripts performing reconnaissance or data exfiltration. It also helps detect malware that uses curl as a download cradle to retrieve additional payloads from external servers.",
    },
    {
        "content": [
            {
                "value": "perl*",
                "label": "http.http_user_agent: perl*",
                "fullString": False,
                "query": "filter",
                "negated": False,
                "id": "http.http_user_agent",
            }
        ],
        "name": "Info: Perl HTTP User Agents",
        "page": "DASHBOARDS",
        "description": "This informational filter highlights the HTTP-based events that contain Perl HTTP User Agents. Use case examples: Hunters can use this filter to detect Perl-based scripts or tools communicating over HTTP, which may indicate automated exploitation tools or legacy malware written in Perl that are still active on older systems. It also helps identify unauthorized scripting activity on systems where Perl execution should not be expected as part of normal operations.",
    },
    {
        "content": [
            {
                "value": "wget*",
                "label": "http.http_user_agent: wget*",
                "fullString": False,
                "query": "filter",
                "negated": False,
                "id": "http.http_user_agent",
            }
        ],
        "name": "Info: Wget HTTP User Agents",
        "page": "DASHBOARDS",
        "description": "This informational filter highlights the HTTP-based events that contain Wget HTTP User Agents. Use case examples: This filter helps identify wget-based download activity that may indicate malware using wget as a download cradle, automated scripts performing unauthorized data collection, or attackers staging payloads on compromised systems. Analysts can use it to detect post-exploitation activity where wget is used to pull tools or secondary payloads from attacker-controlled infrastructure.",
    },
    {
        "content": [
            {
                "id": "alert.signature",
                "value": "*outdated*",
                "label": "alert.signature: *outdated*",
                "fullString": False,
                "negated": False,
            },
        ],
        "name": "Policy: Outdated software",
        "page": "DASHBOARDS",
        "description": "This filter highlights outdated or old software that should be upgraded or patched. Use case examples: Hunters can use this filter to identify network-visible software with known outdated versions that may contain unpatched vulnerabilities, providing input for patch management prioritization. It helps security teams proactively identify attack surface reduction opportunities by surfacing software versions that are known to be targeted by current threat campaigns.",
    },
    {
        "content": [
            {
                "id": "alert.signature",
                "value": "*vulnerable*",
                "label": "alert.signature: *vulnerable*",
                "fullString": False,
                "negated": False,
            },
        ],
        "name": "Policy: Vulnerable software",
        "page": "DASHBOARDS",
        "description": "This filter highlights known-vulnerable software that should be upgraded or patched. Use case examples: This filter helps security teams identify network-visible software with known critical vulnerabilities that are actively being exploited in the wild, enabling immediate prioritization of patching efforts. Analysts can use it to correlate vulnerable software detections with attack events to determine if observed exploitation attempts are targeting specific vulnerable versions present on the network.",
    },
    {
        "content": [
            {
                "id": "alert.signature",
                "value": "*CVE-*",
                "label": "alert.signature: *CVE-*",
                "fullString": False,
                "negated": False,
            },
        ],
        "name": "Policy: CVE global detection",
        "page": "DASHBOARDS",
        "description": "This filter highlights events associated with publicly-identified vulnerabilities (CVE issued). Use case examples: Hunters can use this filter for a broad sweep of all CVE-related exploitation attempts on the network, establishing a baseline of vulnerability exploitation activity and identifying the most targeted systems. It is a critical filter for continuous vulnerability management, helping teams correlate detection events with their patch management program to identify gaps in coverage.",
    },
    {
        "content": [
            {
                "id": "alert.signature",
                "value": "*phishing*",
                "label": "alert.signature: *phishing*",
                "fullString": False,
                "negated": False,
            },
        ],
        "name": "Phishing: Phishing general detection",
        "page": "DASHBOARDS",
        "description": 'This filter highlights events that contain the keyword "phishing", identifying all activity that may be considered possible phishing attempts. Use case examples: This filter provides comprehensive coverage of phishing-related network events, enabling analysts to quickly assess the breadth of phishing activity targeting the organization across multiple protocols and detection methods. Security teams can use it to identify both inbound phishing attempts and outbound connections to phishing infrastructure, supporting both prevention and incident response workflows.',
    },
    {
        "content": [
            {
                "label": "alert.signature: adware_pup",
                "id": "alert.signature",
                "value": "adware_pup",
                "negated": False,
                "query": "filter",
                "fullString": False,
            },
            {
                "id": "alert.category",
                "value": "Possibly Unwanted Program Detected",
                "label": "alert.category: Possibly Unwanted Program Detected",
                "fullString": True,
                "negated": False,
            },
        ],
        "name": "Adware: PUP",
        "page": "DASHBOARDS",
        "description": "Potentially unwanted program (PUP) detected. Usually indicative of policy violation on the network. Use case examples: Security teams can use this filter to identify hosts that have silently installed PUPs through software bundles or drive-by downloads, which are often precursors to more serious malware infections. It helps compliance auditors quickly enumerate policy-violating software installations across the enterprise, enabling targeted remediation efforts.",
    },
    {
        "content": [
            {
                "label": "alert.signature: web_client",
                "id": "alert.signature",
                "value": "web_client",
                "negated": False,
                "query": "filter",
                "fullString": False,
            },
            {
                "id": "alert.signature",
                "value": "*encoded*",
                "label": "alert.signature: *encoded*",
                "fullString": False,
                "negated": False,
            },
        ],
        "name": "Hunt: web client encoded values",
        "page": "DASHBOARDS",
        "description": "This filter highlights the events that have encoded values in the client side HTTP URLs or payload. Use case examples: This filter helps detect client-side injection attacks and web application exploitation attempts where encoded values are embedded in HTTP requests to bypass input validation and web application firewalls. Analysts can use it to identify hosts actively engaged in web application attacks, from SQL injection to cross-site scripting campaigns targeting internal or external web assets.",
    },
    {
        "content": [
            {
                "label": "alert.signature: web_server",
                "id": "alert.signature",
                "value": "web_server",
                "negated": False,
                "query": "filter",
                "fullString": False,
            },
            {
                "id": "alert.signature",
                "value": "*encoded*",
                "label": "alert.signature: *encoded*",
                "fullString": False,
                "negated": False,
            },
        ],
        "name": "Hunt: web server encoded values",
        "page": "DASHBOARDS",
        "description": "This filter highlights the events that have encoded values in the server side HTTP URLs or payload. Use case examples: Hunters can use this filter to detect web servers that are responding with encoded content, which may indicate a compromised server delivering obfuscated malware or redirect scripts to visiting clients. It also helps identify server-side injection attacks and web skimming operations where encoded malicious scripts are being served to unsuspecting users.",
    },
    {
        "content": [
            {
                "label": "alert.signature: shellcode",
                "id": "alert.signature",
                "value": "shellcode",
                "negated": False,
                "query": "filter",
                "fullString": False,
            },
            {
                "id": "alert.signature",
                "value": "*encoded*",
                "label": "alert.signature: *encoded*",
                "fullString": False,
                "negated": False,
            },
        ],
        "name": "Hunt: possible encoded shell code strings",
        "page": "DASHBOARDS",
        "description": "This filter highlights the events that have encoded shellcode string values in the payload. Use case examples: This filter is a strong indicator of active exploitation or post-exploitation activity, as shellcode is typically encoded to evade detection during delivery and injection into vulnerable processes. Analysts can use it to identify the specific network events where shellcode was delivered, enabling precise reconstruction of the exploitation phase of an attack.",
    },
    {
        "content": [
            {
                "label": "es_filter: -http.http_user_agent.keyword:/.{55}.*/",
                "id": "es_filter",
                "value": "-http.http_user_agent.keyword:/.{55}.*/",
                "negated": False,
                "query": "filter",
                "fullString": False,
            },
            {
                "id": "http.http_user_agent",
                "value": "*",
                "label": "http.http_user_agent: *",
                "fullString": False,
                "negated": False,
            },
        ],
        "name": "Hunt: Unusual in length http user agents",
        "page": "DASHBOARDS",
        "description": "This filter highlights the events containing HTTP user agents which contain fewer than 55 characters. Use case examples: Hunters can use this filter to identify anomalously short HTTP user agents, which are frequently used by malware, automated bots, and exploit frameworks that don't bother to mimic legitimate browser user agent strings. It is an effective behavioral indicator for detecting non-browser HTTP clients engaged in malicious activity, from C2 beaconing to credential stuffing.",
    },
    {
        "content": [
            {
                "value": "*java*",
                "label": "http.http_user_agent: *java*",
                "fullString": False,
                "query": "filter",
                "negated": False,
                "id": "http.http_user_agent",
            },
        ],
        "name": "Info: Java HTTP User Agents",
        "page": "DASHBOARDS",
        "description": "This informational filter highlights the HTTP-based events that contain Java HTTP User Agents. Use case examples: This filter helps identify Java-based applications communicating over HTTP, which is valuable for detecting known vulnerable Java frameworks or exploitation of Java deserialization vulnerabilities communicated over HTTP. Analysts can use it to map the Java application footprint on the network and correlate with known CVEs affecting specific Java versions.",
    },
    {
        "content": [
            {
                "id": "http.http_user_agent",
                "value": "*shockwave*",
                "label": "http.http_user_agent: *shockwave*",
                "fullString": False,
                "negated": False,
            },
        ],
        "name": "Info: Shockwave Flash HTTP User Agents",
        "page": "DASHBOARDS",
        "description": "This informational filter highlights the HTTP-based events that contain Shockwave Flash HTTP User Agents. Use case examples: Hunters can use this filter to detect legacy Flash-based applications still communicating on the network, which represents significant risk given that Adobe Flash reached end-of-life and contains numerous unpatched critical vulnerabilities. It helps identify policy violations where Flash remains in use despite organizational directives to remove it, as well as potential exploitation attempts targeting Flash vulnerabilities.",
    },
    {
        "content": [
            {
                "label": "alert.signature: url",
                "id": "alert.signature",
                "value": "url",
                "negated": False,
                "query": "filter",
                "fullString": False,
            },
            {
                "id": "alert.signature",
                "value": "short*",
                "label": "alert.signature: short*",
                "fullString": False,
                "negated": False,
            },
        ],
        "name": "Hunt: URL Shortener services",
        "page": "DASHBOARDS",
        "description": "This filter highlights events that are related to online URL shortening services. Use case examples: Hunters can use this filter to detect the use of URL shortening services that are frequently leveraged in phishing campaigns to mask malicious destination URLs from both users and security tools. It also helps identify policy violations and data exfiltration attempts where URL shorteners are used to obscure external destinations from security monitoring systems.",
    },
    {
        "content": [
            {
                "id": "alert.metadata.stamus_classification",
                "value": "lateral",
                "label": "alert.metadata.stamus_classification: lateral",
                "fullString": True,
                "negated": False,
            },
            {
                "id": "alert.metadata.source",
                "value": "smb_lateral",
                "label": "alert.metadata.source: smb_lateral",
                "fullString": True,
                "negated": False,
            },
            {
                "id": "alert.metadata.signature_severity",
                "value": "Critical",
                "label": "alert.metadata.signature_severity: Critical",
                "fullString": True,
                "negated": False,
            },
        ],
        "name": "Hunt: Stamus critical lateral SMB, DCERPC",
        "page": "DASHBOARDS",
        "description": "This filter highlights SMB critical changes events - deletion/additions/changes/resets/configurations/installations. Use case examples: This filter is critical for detecting destructive or high-impact actions on Active Directory infrastructure, such as account creation, policy changes, or service installations performed via SMB and DCERPC. Security teams can use it to detect ransomware pre-deployment activity, where attackers modify group policies or install malicious services before triggering encryption.",
    },
    {
        "content": [
            {
                "id": "alert.metadata.stamus_classification",
                "value": "lateral",
                "label": "alert.metadata.stamus_classification: lateral",
                "fullString": True,
                "negated": False,
            },
            {
                "id": "alert.metadata.source",
                "value": "smb_lateral",
                "label": "alert.metadata.source: smb_lateral",
                "fullString": True,
                "negated": False,
            },
            {
                "id": "alert.metadata.signature_severity",
                "value": "Informational",
                "label": "alert.metadata.signature_severity: Informational",
                "fullString": True,
                "negated": False,
            },
        ],
        "name": "Hunt: Stamus lateral SMB, DCERPC",
        "page": "DASHBOARDS",
        "description": "This filter highlights SMB informational events. Use case examples: Hunters can use this filter to monitor informational SMB and DCERPC events that provide context about normal and abnormal lateral communication patterns within the Windows environment. It helps establish baseline SMB activity and quickly identify deviations that may indicate credential abuse, unauthorized file access, or reconnaissance operations.",
    },
    {
        "content": [
            {
                "id": "alert.metadata.lateral_function",
                "value": "OpenLocalMachine",
                "label": "alert.metadata.lateral_function: OpenLocalMachine",
                "fullString": True,
                "negated": False,
            },
        ],
        "name": "Hunt: Remote Administration Console OpenLocalMachine",
        "page": "DASHBOARDS",
        "description": "This filter highlights the events that are related to remote administration console being accessed. Use case examples: This filter helps detect unauthorized remote administration activity targeting local machine registry hives, which is a common technique used by attackers to establish persistence or escalate privileges on compromised Windows systems. It also helps identify legitimate but unapproved remote administration tools that may be creating unauthorized access pathways into sensitive systems.",
    },
    {
        "content": [
            {
                "id": "alert.metadata.lateral_function",
                "value": "OpenClassesRoot",
                "label": "alert.metadata.lateral_function: OpenClassesRoot",
                "fullString": True,
                "negated": False,
            },
        ],
        "name": "Hunt: Remote Administration Registry HKEY_CLASSES_ROOT",
        "page": "DASHBOARDS",
        "description": "This filter highlights the events that are related to remote administration registry being accessed. Use case examples: Hunters can use this filter to detect unauthorized registry manipulation via remote administration protocols, which is a key technique used by advanced persistent threats to modify COM objects and establish stealthy persistence mechanisms. It is especially useful for identifying post-exploitation activity where an attacker is remotely configuring Windows registry settings to maintain foothold.",
    },
    {
        "content": [
            {
                "id": "alert.signature",
                "value": "*cleartext*",
                "label": "alert.signature: *cleartext*",
                "fullString": False,
                "negated": False,
            },
            {
                "id": "alert.category",
                "value": "Potential Corporate Privacy Violation",
                "label": "alert.category: Potential Corporate Privacy Violation",
                "fullString": True,
                "negated": False,
            },
        ],
        "name": "Policy: Clear text password - 1",
        "page": "DASHBOARDS",
        "description": "This filter highlights events associated with clear text passwords. Use case examples: This filter helps detect the use of unencrypted authentication protocols where credentials are transmitted in plaintext, creating significant risk of credential theft through network interception. Analysts can use it to identify legacy applications and misconfigured services that are violating organizational security policies by transmitting passwords without encryption.",
    },
    {
        "content": [
            {
                "label": "alert.signature: password",
                "id": "alert.signature",
                "value": "password",
                "negated": False,
                "query": "filter",
                "fullString": False,
            },
            {
                "label": "alert.signature: unencrypted",
                "id": "alert.signature",
                "value": "unencrypted",
                "negated": False,
                "query": "filter",
                "fullString": False,
            },
            {
                "id": "alert.category",
                "value": "Potential Corporate Privacy Violation",
                "label": "alert.category: Potential Corporate Privacy Violation",
                "fullString": True,
                "negated": False,
            },
        ],
        "name": "Policy: Clear text password - 2",
        "page": "DASHBOARDS",
        "description": "This filter highlights events associated with unencrypted passwords. Use case examples: Hunters can use this filter as a complementary sweep to detect additional patterns of unencrypted password transmission not covered by the first filter, ensuring comprehensive coverage of cleartext credential risks. It is especially useful in complex environments where multiple legacy protocols or applications may be transmitting credentials in different unencrypted formats.",
    },
]


class FilterSet(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    content = models.TextField()
    name = models.CharField(max_length=150)
    page = models.CharField(max_length=25)
    description = models.TextField(blank=True, null=True)
    imported = models.BooleanField(default=False)

    @staticmethod
    def get_default_filter_sets() -> list[FilterSetDict]:
        return deepcopy(FILTER_SETS)  # return a copy of the list to avoid unwanted modifications
