# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-13 17:23


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0054_login_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='cats_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='source',
            name='rules_count',
            field=models.IntegerField(default=0),
        ),
    ]
