# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 09:24


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0057_auto_20180302_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='public_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
