# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('rules', '0059_auto_20180309_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActionObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_key', models.CharField(max_length=20)),
                ('action_value', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='action',
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='options',
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='ruleset',
        ),
        migrations.AddField(
            model_name='useraction',
            name='action_type',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='description',
            field=models.CharField(max_length=1512, null=True),
        ),
        migrations.AddField(
            model_name='useractionobject',
            name='user_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_action_objects', to='rules.UserAction'),
        ),
    ]
