# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 08:21


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0061_auto_20180507_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
