# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-18 01:18


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0062_useraction_username'),
        ('rules', '0061_auto_20180503_2200'),
    ]

    operations = [
    ]
