# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 09:09


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0062_useraction_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleProcessingFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[(b'suppress', b'Suppress'), (b'threshold', b'Threshold'), (b'tag', b'Tag'), (b'tagkeep', b'Tag and keep')], max_length=10)),
                ('options', models.CharField(blank=True, max_length=512, null=True)),
                ('index', models.PositiveIntegerField()),
                ('description', models.TextField(default=b'')),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='RuleProcessingFilterDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=512)),
                ('value', models.CharField(max_length=512)),
                ('operator', models.CharField(choices=[(b'equal', b'Equal'), (b'different', b'Different'), (b'contains', b'Contains')], max_length=10)),
                ('proc_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_defs', to='rules.RuleProcessingFilter')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
