# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-19 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0063_merge_20180718_0118'),
        ('rules', '0064_ruleprocessingfilter_rulesets'),
    ]

    operations = [
    ]
