# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-07 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0065_merge_20180719_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rule',
            name='group_by',
            field=models.CharField(choices=[(b'by_src', b'by_src'), (b'by_dst', b'by_dst')], default=b'by_src', max_length=10),
        ),
        migrations.AddField(
            model_name='rule',
            name='group_ips_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
