# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-08 14:15


from django.db import migrations, models

def set_backward_default(apps, schema_editor):
    Source = apps.get_model('rules', 'Source')
    for src in Source.objects.all().iterator():
        src.use_iprep = False
        src.save()

class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0066_auto_20180807_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='use_iprep',
            field=models.BooleanField(default=True, verbose_name=b'Use IP reputation for group signatures'),
        ),
        migrations.RunPython(set_backward_default)
    ]
