# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-18 22:04


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0067_source_use_iprep'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruleprocessingfilterdef',
            options={'ordering': ('key', 'value')},
        ),
    ]
