# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-06 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0069_auto_20190220_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleprocessingfilterdef',
            name='full_string',
            field=models.BooleanField(default=True),
        ),
    ]
