# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-11 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0071_filterset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleprocessingfilter',
            name='action',
            field=models.CharField(choices=[('suppress', 'Suppress'), ('threshold', 'Threshold'), ('tag', 'Tag'), ('tagkeep', 'Tag and keep'), ('send_mail', 'Send email')], max_length=10),
        ),
    ]
