# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-03 13:47


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0072_send_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterset',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
