# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-03 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('rules', '0073_filterset_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraction',
            name='content_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='useraction',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
