# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-18 10:11


from django.db import migrations, models
import rules.models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0074_redlights_useraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='elasticsearch_url',
            field=models.CharField(default='http://elasticsearch:9200/', max_length=200, validators=[rules.models.validate_url]),
        ),
    ]
