# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-16 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import rules.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0074_redlights_useraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold',
            name='net',
            field=models.CharField(blank=True, max_length=100, validators=[rules.validators.validate_addresses_or_networks]),
        ),
    ]
