# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-26 12:33


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0075_custom_es_no_empty'),
        ('rules', '0075_suppress_validator'),
    ]

    operations = [
    ]
