# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-10 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import rules.models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0078_auto_20200206_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='datatype',
            field=models.CharField(max_length=10, validators=[rules.models.validate_source_datatype]),
        ),
    ]
