# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-26 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0079_source_remove_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
