# Generated by Django 2.2.13 on 2020-06-24 11:34

from django.db import migrations, models
import django.utils.timezone
import rules.models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0080_source_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='categorytransformation',
            name='key',
            field=models.CharField(choices=[('action', 'Action'), ('lateral', 'Lateral'), ('target', 'Target'), ('suppressed', 'Suppressed')], default='action', max_length=15),
        ),
        migrations.AlterField(
            model_name='categorytransformation',
            name='value',
            field=models.CharField(default='none', max_length=15),
        ),
        migrations.AlterField(
            model_name='flowbit',
            name='type',
            field=models.CharField(choices=[('flowbits', 'Flowbits'), ('hostbits', 'Hostbits'), ('xbits', 'Xbits')], max_length=12),
        ),
        migrations.AlterField(
            model_name='rule',
            name='group_by',
            field=models.CharField(choices=[('by_src', 'by_src'), ('by_dst', 'by_dst')], default='by_src', max_length=10),
        ),
        migrations.AlterField(
            model_name='ruleprocessingfilter',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ruleprocessingfilterdef',
            name='operator',
            field=models.CharField(choices=[('equal', 'Equal'), ('different', 'Different'), ('contains', 'Contains')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='created_date',
            field=models.DateTimeField(verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='updated_date',
            field=models.DateTimeField(blank=True, verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='rulesettransformation',
            name='key',
            field=models.CharField(choices=[('action', 'Action'), ('lateral', 'Lateral'), ('target', 'Target'), ('suppressed', 'Suppressed')], default='action', max_length=15),
        ),
        migrations.AlterField(
            model_name='rulesettransformation',
            name='value',
            field=models.CharField(default='none', max_length=15),
        ),
        migrations.AlterField(
            model_name='ruletransformation',
            name='key',
            field=models.CharField(choices=[('action', 'Action'), ('lateral', 'Lateral'), ('target', 'Target'), ('suppressed', 'Suppressed')], default='action', max_length=15),
        ),
        migrations.AlterField(
            model_name='ruletransformation',
            name='value',
            field=models.CharField(default='none', max_length=15),
        ),
        migrations.AlterField(
            model_name='source',
            name='cert_verif',
            field=models.BooleanField(default=True, verbose_name='Check certificates'),
        ),
        migrations.AlterField(
            model_name='source',
            name='created_date',
            field=models.DateTimeField(verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='source',
            name='method',
            field=models.CharField(choices=[('http', 'HTTP URL'), ('local', 'Upload')], max_length=10),
        ),
        migrations.AlterField(
            model_name='source',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='source',
            name='use_iprep',
            field=models.BooleanField(default=True, verbose_name='Use IP reputation for group signatures'),
        ),
        migrations.AlterField(
            model_name='sourceatversion',
            name='git_version',
            field=models.CharField(default='HEAD', max_length=42),
        ),
        migrations.AlterField(
            model_name='sourceatversion',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='sourceupdate',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='date of update'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='http_proxy',
            field=models.CharField(blank=True, default='', help_text='Proxy address of the form "host:port".', max_length=200, validators=[rules.models.validate_proxy]),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='https_proxy',
            field=models.CharField(blank=True, default='', max_length=200, validators=[rules.models.validate_proxy]),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='threshold_type',
            field=models.CharField(choices=[('threshold', 'threshold'), ('suppress', 'suppress')], default='suppress', max_length=20),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='track_by',
            field=models.CharField(choices=[('by_src', 'by_src'), ('by_dst', 'by_dst')], default='by_src', max_length=10),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='type',
            field=models.CharField(choices=[('limit', 'limit'), ('threshold', 'threshold'), ('both', 'both')], default='limit', max_length=20),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='event date'),
        ),
    ]
