# Generated by Django 2.2.13 on 2020-11-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0081_django-2'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='use_sys_proxy',
            field=models.BooleanField(default=True, verbose_name='Use system proxy'),
        ),
    ]
