# Generated by Django 2.2.17 on 2020-12-31 16:58

from django.db import migrations, models
import rules.models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0082_source_use_sys_proxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='elasticsearch_url',
            field=models.CharField(default='http://elasticsearch:9200/', max_length=4096, validators=[rules.models.validate_url_list]),
        ),
    ]
