# Generated by Django 2.2.13 on 2020-12-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0083_multi_es_validation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakePermissionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
