# Generated by Django 2.2.17 on 2021-03-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0085_roles_migrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='suppressed_sids',
            field=models.TextField(blank=True, default='', verbose_name='Suppress events'),
        ),
    ]
