# Generated by Django 2.2.17 on 2021-06-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0086_ruleset_suppressed_sids'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='use_proxy_for_es',
            field=models.BooleanField(default=False),
        ),
    ]
