# Generated by Django 2.2.24 on 2021-08-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0089_ruleprocessingfilter_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraction',
            name='client_ip',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
