# Generated by Django 2.2.24 on 2022-03-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0092_auto_20220412_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='custom_cookie_age',
            field=models.FloatField(default=360, verbose_name='Age of session cookies'),
        ),
    ]
