# Generated by Django 3.2.13 on 2022-08-10 14:13

from django.db import migrations, models
import rules.models


def migrate_es_url(apps, schema_editor):
    # Remove usernames and passwords from the urls
    SystemSettings = apps.get_model('rules', 'SystemSettings')
    settings = SystemSettings.objects.first()
    if settings is None:
        settings = SystemSettings.objects.create()

    es_user = ''
    es_pass = ''
    if '@' in settings.elasticsearch_url:
        urls = []
        for url in settings.elasticsearch_url.split(','):
            scheme = ''
            if '://' in url:
                scheme, url = url.split('://', 1)
                scheme += '://'
            if '@' in url:
                creds, url = url.split('@', 1)
                es_user, es_pass = creds.split(':', 1)
            urls.append(scheme + url)

        settings.elasticsearch_url = ','.join(urls)
        settings.elasticsearch_user = es_user
        settings.elasticsearch_pass = es_pass
        settings.save()


def revert_es_url(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0093_systemsettings_custom_cookie_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='elasticsearch_pass',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='Elasticsearch password'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='elasticsearch_user',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='Elasticsearch username'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='elasticsearch_url',
            field=models.CharField(default='http://elasticsearch:9200/', help_text='Comma separated list of elasticsearch url', max_length=4096, validators=[rules.models.validate_url_list]),
        ),
        migrations.RunPython(migrate_es_url, revert_es_url)
    ]
