# Generated by Django 3.2.15 on 2022-09-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0094_elasticsearch_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='activate_categories',
            field=models.BooleanField(default=True),
        ),
    ]
