# Generated by Django 3.2.15 on 2022-09-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0095_ruleset_activate_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='custom_login_banner',
            field=models.TextField(blank=True, default='', verbose_name='Add your own banner on login page'),
        ),
    ]
