# Generated by Django 3.2.16 on 2022-11-21 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0096_systemsettings_custom_login_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='cats_count',
        ),
        migrations.RemoveField(
            model_name='source',
            name='rules_count',
        ),
    ]
