# Generated by Django 3.2.16 on 2022-12-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0097_auto_20221121_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='untrusted',
            field=models.BooleanField(default=True, verbose_name='Supply chain attack protection'),
        ),
    ]
