# Generated by Django 3.2.16 on 2023-02-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0098_source_trusted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='datatype',
            field=models.CharField(max_length=10),
        ),
    ]
