# Generated by Django 3.2.18 on 2023-10-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0101_auto_20230626_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='session_cookie_age',
            field=models.IntegerField(default=0),
        ),
    ]
