# Generated by Django 3.2.18 on 2023-06-26 16:24

import os
import shutil
from django.db import migrations, models
from django.conf import settings


ruleset_source_map = {}


def migration_1(apps, _):
    Ruleset = apps.get_model('rules', 'Ruleset')

    for ruleset in Ruleset.objects.all():
        ruleset_source_map.update({
            ruleset.pk: list(ruleset.sources.values_list('source_id', flat=True))
        })


def migration_2(apps, _):
    Ruleset = apps.get_model('rules', 'Ruleset')
    Source = apps.get_model('rules', 'Source')

    for ruleset_pk, sources_pk in ruleset_source_map.items():
        ruleset = Ruleset.objects.get(pk=ruleset_pk)
        ruleset.sources.set(Source.objects.filter(pk__in=sources_pk))

    if not os.path.exists(settings.GIT_SOURCES_BASE_DIRECTORY):
        return

    # remove git directories
    for item in os.listdir(settings.GIT_SOURCES_BASE_DIRECTORY):
        full_path = os.path.join(settings.GIT_SOURCES_BASE_DIRECTORY, item)
        if os.path.isdir(full_path) and item.isdigit():
            git_path = os.path.join(full_path, '.git')
            if os.path.exists(git_path):
                shutil.rmtree(git_path, ignore_errors=True)


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0101_rule_content'),
    ]

    operations = [
        migrations.RunPython(migration_1),

        migrations.AlterField(
            model_name='ruleset',
            name='sources',
            field=models.ManyToManyField(to='rules.Source'),
        ),

        migrations.RunPython(migration_2),

        migrations.RemoveField(
            model_name='sourceupdate',
            name='version',
        ),
        migrations.DeleteModel(
            name='SourceAtVersion',
        ),
    ]
