# Generated by Django 3.2.20 on 2023-10-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0102_auto_20230626_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='sid',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
