# Generated by Django 3.2.20 on 2024-02-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0103_alter_rule_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleatversion',
            name='analysis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
