# Generated by Django 3.2.25 on 2024-05-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0104_ruleatversion_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='is_stamus',
            field=models.BooleanField(default=False),
        ),
    ]
