# Generated by Django 3.2.25 on 2024-06-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0105_source_is_stamus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleprocessingfilterdef',
            name='value',
            field=models.CharField(max_length=1024),
        ),
    ]
