# Generated by Django 3.2.25 on 2024-07-23 07:48

from django.db import migrations, models
import rules.models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0106_alter_ruleprocessingfilterdef_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeepLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('template', models.CharField(max_length=2048, validators=[rules.models.validate_url])),
                ('all', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('name', 'template')},
            },
        ),
        migrations.CreateModel(
            name='DeepLinkEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('deeplink', models.ManyToManyField(blank=True, related_name='entities', to='rules.DeepLink')),
            ],
        ),
    ]
