# Generated by Django 3.2.25 on 2024-09-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0107_deeplink_deeplinkentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
