# Generated by Django 4.2.18 on 2025-01-21 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0109_source_remove_original_sids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruleset',
            name='need_test',
        ),
    ]
