# Generated by Django 4.2.18 on 2025-03-03 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0110_remove_ruleset_need_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='use_elasticsearch',
        ),
    ]
