# Generated by Django 4.2.18 on 2025-02-17 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0111_remove_systemsettings_use_elasticsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='ioc_type',
            field=models.CharField(blank=True, choices=[
                ('hostname', 'Hostname'),
                ('domain_name', 'Domain Name'),
                ('ip', 'IP'),
            ], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='IoCMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('ioc_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ioc_meta', to='rules.source')),
            ],
        ),
    ]
