# Generated by Django 4.2.18 on 2025-04-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0112_source_ioc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='ioc_type',
            field=models.CharField(blank=True, choices=[('hostname', 'Hostname'), ('domain_name', 'Domain Name'), ('ip', 'IP'), ('filename', 'Filename'), ('url', 'URL'), ('http-user-agent', 'HTTP User Agent'), ('http-cookie', 'HTTP Cookie')], max_length=20, null=True),
        ),
    ]
