# Generated by Django 4.2.25 on 2025-11-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0114_deeplinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='ssl_proxy',
            field=models.BooleanField(default=True, help_text='Verify proxy SSL, must be disabled for self signed certificates'),
        ),
    ]
