# Generated by Django 4.2.25 on 2026-03-10 14:03

from django.db import migrations, models
import django.utils.timezone


def get_dates_from_user_actions(apps, schema_editor):
    UserActionObject = apps.get_model('rules', 'UserActionObject')
    RuleProcessingFilter = apps.get_model('rules', 'RuleProcessingFilter')
    objects = UserActionObject.objects.select_related("user_action").filter(user_action__action_type="create_rule_filter", action_key="rule_filter")
    for uao in objects.iterator(chunk_size=512):
        RuleProcessingFilter.objects.filter(pk=uao.object_id).update(creation_date=uao.user_action.date)


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0115_systemsettings_ssl_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleprocessingfilter',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
        migrations.RunPython(get_dates_from_user_actions),
    ]
