# manual way of starting the container (otherwise see docker-compose.ui.yml):
# docker build -f Dockerfile.ui.dev -t tzetzo/ui .
# docker run -p 3003:3000 tzetzo/ui

FROM debian:buster

WORKDIR /app

RUN apt-get update &&\
    apt-get install -y nodejs &&\
    apt-get install -y npm --fix-missing &&\
    apt-get install -y ssh rsync

COPY . .

WORKDIR /app/ui

RUN npm install

CMD ["npm", "start"]
