# make sure you are on the master branch
# docker-compose up
# docker-compose -f docker-compose.ui.yml up --build

version: '3'
services:
  # ui container
  ui:
    build:
      context: ../
      dockerfile: ./ui/Dockerfile.ui.dev
    restart: always
    ports:
      - '3003:3000'
    stdin_open: true # React dev server exits without this
    # Any changes inside the Scirius project folder will be reflected in the corresponding Scirius folder inside the Container(/app):
    volumes:
      - /app/node_modules # excludes this folder from the mounting
      - /app/ui/node_modules # excludes this folder from the mounting
      - ../:/app
