export const ACTION_TYPES_LOADING = 'Hunt/HistoryPage/GET_ACTION_TYPES_LOADING';
export const ACTION_TYPES_SUCCESS = 'Hunt/HistoryPage/GET_ACTION_TYPES_SUCCESS';
export const ACTION_TYPES_FAIL = 'Hunt/HistoryPage/GET_ACTION_TYPES_FAIL';
